<a href="https://colab.research.google.com/github/Bhakti77/pandas/blob/main/Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd

data = {
    'name':       ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Karan',
                   'Nisha', 'Amit', 'Pooja', 'Vikram', 'Anjali'],
    'city':       ['Mumbai', 'Pune', 'Delhi', 'Bangalore', 'Mumbai',
                   'Chennai', 'Pune', 'Mumbai', 'Delhi', 'Bangalore'],
    'category':   ['Electronics', 'Appliances', 'Electronics', 'Fitness',
                   'Electronics', 'Appliances', 'Fitness', 'Electronics',
                   'Fitness', 'Appliances'],
    'sales':      [75000, 3500, 82000, 1200, 45000,
                   4500, 6000, 45000, 3200, 12000],
    'rating':     [4.5, 3.2, None, 5.0, 2.8,
                   None, 4.1, 3.9, None, 4.7]
}

df = pd.DataFrame(data)
print(df)

     name       city     category  sales  rating
0   Aarav     Mumbai  Electronics  75000     4.5
1   Priya       Pune   Appliances   3500     3.2
2   Rohan      Delhi  Electronics  82000     NaN
3   Sneha  Bangalore      Fitness   1200     5.0
4   Karan     Mumbai  Electronics  45000     2.8
5   Nisha    Chennai   Appliances   4500     NaN
6    Amit       Pune      Fitness   6000     4.1
7   Pooja     Mumbai  Electronics  45000     3.9
8  Vikram      Delhi      Fitness   3200     NaN
9  Anjali  Bangalore   Appliances  12000     4.7

In [43]:
#attributes
df.shape
df.columns
# df.columns.tolist()
df.index
df.dtypes
df.info()
df.describe() #summarize only numeric columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   city      10 non-null     object
 2   category  10 non-null     object
 3   sales     10 non-null     int64
 4   rating    7 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 532.0+ bytes

             sales    rating
count     10.00000  7.000000
mean   27740.00000  4.028571
std    31496.21494  0.799405
min     1200.00000  2.800000
25%     3750.00000  3.550000
50%     9000.00000  4.100000
75%    45000.00000  4.600000
max    82000.00000  5.000000

In [44]:
#Accessing data
# df['name']
type[df['name']]

type[0     Aarav
1     Priya
2     Rohan
3     Sneha
4     Karan
5     Nisha
6      Amit
7     Pooja
8    Vikram
9    Anjali
Name: name, dtype: object]

In [45]:
df['name'].value_counts()

name
Aarav     1
Priya     1
Rohan     1
Sneha     1
Karan     1
Nisha     1
Amit      1
Pooja     1
Vikram    1
Anjali    1
Name: count, dtype: int64

In [46]:
df[['name','sales']]
type(df[['name','sales']])

pandas.core.frame.DataFrame

In [47]:
df.iloc[0]
df.iloc[0, 1]   # first row, second column

'Mumbai'

In [48]:
#Adding a column
df['tax'] = df['sales']*0.18
df.head()

    name       city     category  sales  rating      tax
0  Aarav     Mumbai  Electronics  75000     4.5  13500.0
1  Priya       Pune   Appliances   3500     3.2    630.0
2  Rohan      Delhi  Electronics  82000     NaN  14760.0
3  Sneha  Bangalore      Fitness   1200     5.0    216.0
4  Karan     Mumbai  Electronics  45000     2.8   8100.0

In [49]:
df['Country'] = 'India'
df

     name       city     category  sales  rating      tax Country
0   Aarav     Mumbai  Electronics  75000     4.5  13500.0   India
1   Priya       Pune   Appliances   3500     3.2    630.0   India
2   Rohan      Delhi  Electronics  82000     NaN  14760.0   India
3   Sneha  Bangalore      Fitness   1200     5.0    216.0   India
4   Karan     Mumbai  Electronics  45000     2.8   8100.0   India
5   Nisha    Chennai   Appliances   4500     NaN    810.0   India
6    Amit       Pune      Fitness   6000     4.1   1080.0   India
7   Pooja     Mumbai  Electronics  45000     3.9   8100.0   India
8  Vikram      Delhi      Fitness   3200     NaN    576.0   India
9  Anjali  Bangalore   Appliances  12000     4.7   2160.0   India

In [50]:
df = df.drop(columns='tax') #drop does not modify original, it returns new df,
#here assigned to original df itself so original can get mofified

In [51]:
df.head()

    name       city     category  sales  rating Country
0  Aarav     Mumbai  Electronics  75000     4.5   India
1  Priya       Pune   Appliances   3500     3.2   India
2  Rohan      Delhi  Electronics  82000     NaN   India
3  Sneha  Bangalore      Fitness   1200     5.0   India
4  Karan     Mumbai  Electronics  45000     2.8   India

In [52]:
df = df.drop(columns='Country')
df.head()

    name       city     category  sales  rating
0  Aarav     Mumbai  Electronics  75000     4.5
1  Priya       Pune   Appliances   3500     3.2
2  Rohan      Delhi  Electronics  82000     NaN
3  Sneha  Bangalore      Fitness   1200     5.0
4  Karan     Mumbai  Electronics  45000     2.8

In [53]:
#Filtering rows
df['city'] == 'Mumbai' #only give true or false
df[df['city'] == 'Mumbai'] #actually filteres the data

    name    city     category  sales  rating
0  Aarav  Mumbai  Electronics  75000     4.5
4  Karan  Mumbai  Electronics  45000     2.8
7  Pooja  Mumbai  Electronics  45000     3.9

In [54]:
df[df['sales']>10000]

     name       city     category  sales  rating
0   Aarav     Mumbai  Electronics  75000     4.5
2   Rohan      Delhi  Electronics  82000     NaN
4   Karan     Mumbai  Electronics  45000     2.8
7   Pooja     Mumbai  Electronics  45000     3.9
9  Anjali  Bangalore   Appliances  12000     4.7

In [55]:
df[(df['city']=='Mumbai') & (df['sales']>10000)]

    name    city     category  sales  rating
0  Aarav  Mumbai  Electronics  75000     4.5
4  Karan  Mumbai  Electronics  45000     2.8
7  Pooja  Mumbai  Electronics  45000     3.9

In [56]:
df[(df['city'] == 'Mumbai') | (df['city'] == 'Pune')]

    name    city     category  sales  rating
0  Aarav  Mumbai  Electronics  75000     4.5
1  Priya    Pune   Appliances   3500     3.2
4  Karan  Mumbai  Electronics  45000     2.8
6   Amit    Pune      Fitness   6000     4.1
7  Pooja  Mumbai  Electronics  45000     3.9

In [59]:
df[~(df['city'] == 'Mumbai')]

     name       city     category  sales  rating
1   Priya       Pune   Appliances   3500     3.2
2   Rohan      Delhi  Electronics  82000     NaN
3   Sneha  Bangalore      Fitness   1200     5.0
5   Nisha    Chennai   Appliances   4500     NaN
6    Amit       Pune      Fitness   6000     4.1
8  Vikram      Delhi      Fitness   3200     NaN
9  Anjali  Bangalore   Appliances  12000     4.7

In [62]:
#handling nulls
df.isnull()
df.isnull().sum()

name        0
city        0
category    0
sales       0
rating      3
dtype: int64

In [63]:
#drop nulls
df.dropna()

     name       city     category  sales  rating
0   Aarav     Mumbai  Electronics  75000     4.5
1   Priya       Pune   Appliances   3500     3.2
3   Sneha  Bangalore      Fitness   1200     5.0
4   Karan     Mumbai  Electronics  45000     2.8
6    Amit       Pune      Fitness   6000     4.1
7   Pooja     Mumbai  Electronics  45000     3.9
9  Anjali  Bangalore   Appliances  12000     4.7

In [64]:
df.shape #drop returns new dataframe so original was unchanged

(10, 5)

In [66]:
df['rating'].fillna(df['rating'].mean())

#In real DA work filling with mean or median is called imputation —
#a standard data cleaning technique.Because 0 is misleading — a rating of 0 doesn't exist in reality, it would skew your analysis.
#If someone calculates average rating, 0 would pull it down unfairly.

0    4.500000
1    3.200000
2    4.028571
3    5.000000
4    2.800000
5    4.028571
6    4.100000
7    3.900000
8    4.028571
9    4.700000
Name: rating, dtype: float64

In [67]:
df['rating'] = df['rating'].fillna(df['rating'].mean())
df.isnull().sum()

name        0
city        0
category    0
sales       0
rating      0
dtype: int64

In [69]:
#Aggregations

#basics
df['sales'].sum()    # total sales
df['sales'].mean()   # average sales
df['sales'].max()    # highest sale
df['sales'].min()    # lowest sale
df['sales'].count()  # number of values

np.int64(277400)

In [70]:
df['sales'].describe()

count       10.00000
mean     27740.00000
std      31496.21494
min       1200.00000
25%       3750.00000
50%       9000.00000
75%      45000.00000
max      82000.00000
Name: sales, dtype: float64

In [71]:
#GROUPBY - most powerful aggregation
df.groupby('city')['sales'].sum()

city
Bangalore     13200
Chennai        4500
Delhi         85200
Mumbai       165000
Pune           9500
Name: sales, dtype: int64

In [72]:
df.groupby('category')['sales'].sum() # avg sales per category

category
Appliances      20000
Electronics    247000
Fitness         10400
Name: sales, dtype: int64

In [74]:
df.groupby('city')['sales'].count() # number of orders per city

city
Bangalore    2
Chennai      1
Delhi        2
Mumbai       3
Pune         2
Name: sales, dtype: int64

In [78]:
#Sorting
df.sort_values(by='sales') #default ascending
df.sort_values('sales', ascending=False)

     name       city     category  sales    rating
2   Rohan      Delhi  Electronics  82000  4.028571
0   Aarav     Mumbai  Electronics  75000  4.500000
7   Pooja     Mumbai  Electronics  45000  3.900000
4   Karan     Mumbai  Electronics  45000  2.800000
9  Anjali  Bangalore   Appliances  12000  4.700000
6    Amit       Pune      Fitness   6000  4.100000
5   Nisha    Chennai   Appliances   4500  4.028571
1   Priya       Pune   Appliances   3500  3.200000
8  Vikram      Delhi      Fitness   3200  4.028571
3   Sneha  Bangalore      Fitness   1200  5.000000