<a href="https://colab.research.google.com/github/Bhakti77/pandas/blob/main/pandas_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Reshaping data
#melt()
#melt() converts a wide DataFrame to long format — opposite of pivot table.
import pandas as pd
wide_df = pd.DataFrame({
    'customer': ['Aarav', 'Priya', 'Rohan'],
    'jan_sales': [1000, 2000, 1500],
    'feb_sales': [1200, 1800, 1700],
    'mar_sales': [900, 2200, 1600]
})
wide_df

  customer  jan_sales  feb_sales  mar_sales
0    Aarav       1000       1200        900
1    Priya       2000       1800       2200
2    Rohan       1500       1700       1600

In [9]:
long_df = wide_df.melt(id_vars='customer',var_name='month',value_name='sales')

In [13]:
long_df.groupby('month')['sales'].sum()   # total sales per month
#long_df.groupby('customer')['sales'].mean()  # avg sales per customer

month
feb_sales    4700
jan_sales    4500
mar_sales    4700
Name: sales, dtype: int64

In [14]:
#pivot - opposite of melt, converts long form back to wide format
long_df.pivot(index='customer', columns='month', values='sales')

month     feb_sales  jan_sales  mar_sales
customer
Aarav          1200       1000        900
Priya          1800       2000       2200
Rohan          1700       1500       1600

In [15]:
#apply in dataframes
df = pd.DataFrame({
    'q1_sales': [1000, 2000, 1500],
    'q2_sales': [1200, 1800, 1700],
    'q3_sales': [900, 2200, 1600]
}, index=['Aarav', 'Priya', 'Rohan'])

df

       q1_sales  q2_sales  q3_sales
Aarav      1000      1200       900
Priya      2000      1800      2200
Rohan      1500      1700      1600

In [19]:
df.apply('sum')

q1_sales    4500
q2_sales    4700
q3_sales    4700
dtype: int64