<a href="https://colab.research.google.com/github/Bhakti77/pandas/blob/main/Pandas_Intermediate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

data = {
    'order_id':   [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'customer':   ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Karan',
                   'Nisha', 'Amit', 'Pooja', 'Vikram', 'Anjali'],
    'city':       ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Bangalore',
                   'Delhi', None, 'Mumbai', 'Bangalore', 'Delhi'],
    'category':   ['Electronics', 'Appliances', 'Electronics', 'Fitness',
                   'Electronics', 'Appliances', 'Fitness', 'Electronics',
                   None, 'Appliances'],
    'amount':     [75000, 3500, 82000, 1200, 45000,
                   None, 6000, 45000, 3200, 12000],
    'status':     ['delivered', 'delivered', 'pending', None, 'cancelled',
                   'delivered', 'pending', 'delivered', 'cancelled', 'delivered']
}

df = pd.DataFrame(data)
df

   order_id customer       city     category   amount     status
0       101    Aarav     Mumbai  Electronics  75000.0  delivered
1       102    Priya       Pune   Appliances   3500.0  delivered
2       103    Rohan      Delhi  Electronics  82000.0    pending
3       104    Sneha     Mumbai      Fitness   1200.0       None
4       105    Karan  Bangalore  Electronics  45000.0  cancelled
5       106    Nisha      Delhi   Appliances      NaN  delivered
6       107     Amit       None      Fitness   6000.0    pending
7       108    Pooja     Mumbai  Electronics  45000.0  delivered
8       109   Vikram  Bangalore         None   3200.0  cancelled
9       110   Anjali      Delhi   Appliances  12000.0  delivered

In [3]:
df.isnull().sum()

order_id    0
customer    0
city        1
category    1
amount      1
status      1
dtype: int64

In [5]:
#agg - multiple aggregation same time

df.groupby('city')['amount'].agg(
    total_sales = 'sum',
    avg_sales = 'mean',
    max_sales = 'max'
)

           total_sales  avg_sales  max_sales
city
Bangalore      48200.0    24100.0    45000.0
Delhi          94000.0    47000.0    82000.0
Mumbai        121200.0    40400.0    75000.0
Pune            3500.0     3500.0     3500.0

In [9]:
#multiple column in agg - amount and order_id
df.groupby('city').agg(
    total_amount  = ('amount', 'sum'),
    avg_amount    = ('amount', 'mean'),
    order_count   = ('order_id', 'count')
)

           total_amount  avg_amount  order_count
city
Bangalore       48200.0     24100.0            2
Delhi           94000.0     47000.0            3
Mumbai         121200.0     40400.0            3
Pune             3500.0      3500.0            1

In [10]:
#transform
df['city_total'] = df.groupby('city')['amount'].transform('sum')
df[['customer', 'city', 'amount', 'city_total']]

  customer       city   amount  city_total
0    Aarav     Mumbai  75000.0    121200.0
1    Priya       Pune   3500.0      3500.0
2    Rohan      Delhi  82000.0     94000.0
3    Sneha     Mumbai   1200.0    121200.0
4    Karan  Bangalore  45000.0     48200.0
5    Nisha      Delhi      NaN     94000.0
6     Amit       None   6000.0         NaN
7    Pooja     Mumbai  45000.0    121200.0
8   Vikram  Bangalore   3200.0     48200.0
9   Anjali      Delhi  12000.0     94000.0

In [12]:
df['category_total'] = df.groupby('category')['amount'].transform('sum')
df['pct_of_category'] = df['amount'] / df['category_total'] * 100
df[['customer', 'category', 'amount', 'category_total', 'pct_of_category']]

  customer     category   amount  category_total  pct_of_category
0    Aarav  Electronics  75000.0        247000.0        30.364372
1    Priya   Appliances   3500.0         15500.0        22.580645
2    Rohan  Electronics  82000.0        247000.0        33.198381
3    Sneha      Fitness   1200.0          7200.0        16.666667
4    Karan  Electronics  45000.0        247000.0        18.218623
5    Nisha   Appliances      NaN         15500.0              NaN
6     Amit      Fitness   6000.0          7200.0        83.333333
7    Pooja  Electronics  45000.0        247000.0        18.218623
8   Vikram         None   3200.0             NaN              NaN
9   Anjali   Appliances  12000.0         15500.0        77.419355

In [ ]:
df['pct_of_category'] = df['amount'] / df['city_total'] * 100
df[['customer', 'city', 'amount', 'city_total', 'pct_of_city']]

In [16]:
#Handling duplicates
import pandas as pd
import numpy as np

data = {
    'order_id':   [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'customer':   ['Aarav', 'Priya', 'Rohan', 'Sneha', 'Karan',
                   'Nisha', 'Amit', 'Pooja', 'Vikram', 'Anjali'],
    'city':       ['Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Bangalore',
                   'Delhi', None, 'Mumbai', 'Bangalore', 'Delhi'],
    'category':   ['Electronics', 'Appliances', 'Electronics', 'Fitness',
                   'Electronics', 'Appliances', 'Fitness', 'Electronics',
                   None, 'Appliances'],
    'amount':     [75000, 3500, 82000, 1200, 45000,
                   None, 6000, 45000, 3200, 12000],
    'status':     ['delivered', 'delivered', 'pending', None, 'cancelled',
                   'delivered', 'pending', 'delivered', 'cancelled', 'delivered']
}

df = pd.DataFrame(data)

# add duplicates
duplicate_rows = df.iloc[[0, 2]]
df = pd.concat([df, duplicate_rows], ignore_index=True)
df.shape

(12, 6)

In [19]:
df.duplicated().sum()

np.int64(2)

In [20]:
df[df.duplicated()]

    order_id customer    city     category   amount     status
10       101    Aarav  Mumbai  Electronics  75000.0  delivered
11       103    Rohan   Delhi  Electronics  82000.0    pending

In [22]:
df = df.drop_duplicates() #can pass column names as subset as well, it check full combination
df.shape

(10, 6)

In [23]:
#Type conversion
#astype

df.dtypes

order_id      int64
customer     object
city         object
category     object
amount      float64
status       object
dtype: object

In [24]:
df['order_id'] = df['order_id'].astype(str)
df.dtypes

/tmp/ipykernel_439/915971396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['order_id'] = df['order_id'].astype(str)

order_id     object
customer     object
city         object
category     object
amount      float64
status       object
dtype: object

In [26]:
df['status'] = df['status'].astype('category')
df['status'].dtype

/tmp/ipykernel_439/96817649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['status'] = df['status'].astype('category')

CategoricalDtype(categories=['cancelled', 'delivered', 'pending'], ordered=False, categories_dtype=object)

In [35]:
#concat -Used to combine two or more DataFrames by stacking them on top of each other (or side by side).

df1 = pd.DataFrame({
    'order_id': [111, 112,113],
    'customer': ['Rahul', 'Meera','Vikrant'],
    'city':     ['Nagpur', 'Surat','Jaipur'],
    'amount':   [5000, 8000,12000]
})

df2 = pd.DataFrame({
    'order_id': [113, 114],
    'customer': ['Vikrant', 'Kavya'],
    'city':     ['Jaipur', 'Kolkata'],
    'amount':   [12000, 9000]
})

In [36]:
pd.concat([df1, df2],ignore_index=True)

   order_id customer     city  amount
0       111    Rahul   Nagpur    5000
1       112    Meera    Surat    8000
2       113  Vikrant   Jaipur   12000
3       113  Vikrant   Jaipur   12000
4       114    Kavya  Kolkata    9000

In [37]:
pd.concat([df, df1, df2], ignore_index=True) #can work if df has different structure

   order_id customer       city     category   amount     status
0       101    Aarav     Mumbai  Electronics  75000.0  delivered
1       102    Priya       Pune   Appliances   3500.0  delivered
2       103    Rohan      Delhi  Electronics  82000.0    pending
3       104    Sneha     Mumbai      Fitness   1200.0        NaN
4       105    Karan  Bangalore  Electronics  45000.0  cancelled
5       106    Nisha      Delhi   Appliances      NaN  delivered
6       107     Amit       None      Fitness   6000.0    pending
7       108    Pooja     Mumbai  Electronics  45000.0  delivered
8       109   Vikram  Bangalore         None   3200.0  cancelled
9       110   Anjali      Delhi   Appliances  12000.0  delivered
10      111    Rahul     Nagpur          NaN   5000.0        NaN
11      112    Meera      Surat          NaN   8000.0        NaN
12      113  Vikrant     Jaipur          NaN  12000.0        NaN
13      113  Vikrant     Jaipur          NaN  12000.0        NaN
14      114    Kavya    Kolkata          NaN   9000.0        NaN

In [40]:
#WINDOW FUNCTIONS
#rank() and rolling()

df['amount_rank'] = df['amount'].rank(ascending=False)
df=df.sort_values('amount_rank')
df[['customer', 'amount', 'amount_rank']]

  customer   amount  amount_rank
2    Rohan  82000.0          1.0
0    Aarav  75000.0          2.0
7    Pooja  45000.0          3.5
4    Karan  45000.0          3.5
9   Anjali  12000.0          5.0
6     Amit   6000.0          6.0
1    Priya   3500.0          7.0
8   Vikram   3200.0          8.0
3    Sneha   1200.0          9.0
5    Nisha      NaN          NaN

In [41]:
#rank within groups
df['rank_in_city'] = df.groupby('city')['amount'].rank(ascending=False)
df[['customer', 'city', 'amount', 'rank_in_city']]

  customer       city   amount  rank_in_city
2    Rohan      Delhi  82000.0           1.0
0    Aarav     Mumbai  75000.0           1.0
7    Pooja     Mumbai  45000.0           2.0
4    Karan  Bangalore  45000.0           1.0
9   Anjali      Delhi  12000.0           2.0
6     Amit       None   6000.0           NaN
1    Priya       Pune   3500.0           1.0
8   Vikram  Bangalore   3200.0           2.0
3    Sneha     Mumbai   1200.0           3.0
5    Nisha      Delhi      NaN           NaN

In [42]:
df[df['rank_in_city'] == 1][['customer', 'city', 'amount']]

  customer       city   amount
2    Rohan      Delhi  82000.0
0    Aarav     Mumbai  75000.0
4    Karan  Bangalore  45000.0
1    Priya       Pune   3500.0

In [ ]:
#Rolling