<a href="https://colab.research.google.com/github/Bhakti77/pandas/blob/main/pandas_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Reshaping data
#melt()
#melt() converts a wide DataFrame to long format — opposite of pivot table.
import pandas as pd
wide_df = pd.DataFrame({
    'customer': ['Aarav', 'Priya', 'Rohan'],
    'jan_sales': [1000, 2000, 1500],
    'feb_sales': [1200, 1800, 1700],
    'mar_sales': [900, 2200, 1600]
})
wide_df

  customer  jan_sales  feb_sales  mar_sales
0    Aarav       1000       1200        900
1    Priya       2000       1800       2200
2    Rohan       1500       1700       1600

In [9]:
long_df = wide_df.melt(id_vars='customer',var_name='month',value_name='sales')

In [13]:
long_df.groupby('month')['sales'].sum()   # total sales per month
#long_df.groupby('customer')['sales'].mean()  # avg sales per customer

month
feb_sales    4700
jan_sales    4500
mar_sales    4700
Name: sales, dtype: int64

In [14]:
#pivot - opposite of melt, converts long form back to wide format
long_df.pivot(index='customer', columns='month', values='sales')

month     feb_sales  jan_sales  mar_sales
customer
Aarav          1200       1000        900
Priya          1800       2000       2200
Rohan          1700       1500       1600

In [15]:
#apply in dataframes
df = pd.DataFrame({
    'q1_sales': [1000, 2000, 1500],
    'q2_sales': [1200, 1800, 1700],
    'q3_sales': [900, 2200, 1600]
}, index=['Aarav', 'Priya', 'Rohan'])

df

       q1_sales  q2_sales  q3_sales
Aarav      1000      1200       900
Priya      2000      1800      2200
Rohan      1500      1700      1600

In [19]:
df.apply('sum')

q1_sales    4500
q2_sales    4700
q3_sales    4700
dtype: int64

In [22]:
# row-wise — axis=1
df.apply('sum', axis=1)

Aarav    3100
Priya    6000
Rohan    4800
dtype: int64

In [ ]:
#Method chaining
result = (df
    .query('amount > 5000')
    .groupby('city')['amount']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)
result
#one pipeline instead of 4 diff results — much more readable.

In [ ]:
#query() — cleaner filtering
Instead of:
pythondf[df['amount'] > 5000]
Use:
pythondf.query('amount > 5000')
df.query('city == "Mumbai"')
df.query('amount > 5000 and city == "Mumbai"')
More readable — especially in chains.

In [26]:
#Time Series

import pandas as pd
import numpy as np

dates = pd.date_range('2024-01-01', periods=365, freq='D')

ts = pd.DataFrame({
    'date':   dates,
    'sales':  np.random.randint(1000, 5000, 365),
    'orders': np.random.randint(10, 100, 365)
})

ts = ts.set_index('date')
ts.head()

            sales  orders
date
2024-01-01   1438      86
2024-01-02   3004      26
2024-01-03   2968      87
2024-01-04   1031      61
2024-01-05   4571      75

In [24]:
# monthly total sales
ts.resample('ME').sum()

             sales  orders
date
2024-01-31   91703    1657
2024-02-29   76052    1643
2024-03-31  101300    1811
2024-04-30   86650    1469
2024-05-31   89323    1557
2024-06-30   99646    1844
2024-07-31   94953    1799
2024-08-31   99423    1946
2024-09-30   89738    1693
2024-10-31   94574    1631
2024-11-30   82748    1731
2024-12-31   84458    1707

In [28]:
#weekly average
ts.resample('QE').mean()

                  sales     orders
date
2024-03-31  3005.945055  56.505495
2024-06-30  3024.274725  47.615385
2024-09-30  2840.532609  55.380435
2024-12-31  3079.043956  56.153846

In [ ]:
#Performance tips